apiVersion: v1
kind: ConfigMap
metadata:
  name: flood-forecasting-config
  labels:
    app: flood-forecasting
data:
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET_NAME: "flood-data"
  MINIO_SECURE: "True" # Always use secure in production K8s
  REDIS_URL: "redis://redis:6379/0"
