apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: flood-forecasting
    component: minio
spec:
  selector:
    app: flood-forecasting
    component: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
